// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFkUYOiZfY9jj3Y1MK5HSUJpaC9hy760Q',
    appId: '1:915333937006:android:3de12a122f418f2b3db37f',
    messagingSenderId: '915333937006',
    projectId: 'zaitoon-44f50',
    storageBucket: 'zaitoon-44f50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_88BoC0mexY7ZVqkyyA46cu1ZYDXy04U',
    appId: '1:915333937006:ios:14928f36e839a6b43db37f',
    messagingSenderId: '915333937006',
    projectId: 'zaitoon-44f50',
    storageBucket: 'zaitoon-44f50.firebasestorage.app',
    androidClientId: '915333937006-7mhd9pvte078u8u8oom2tcc8s33bna9u.apps.googleusercontent.com',
    iosClientId: '915333937006-nls5f6rhqnam3o3pjvrraqd9am3g76tq.apps.googleusercontent.com',
    iosBundleId: 'com.zaitoonpharmacy.customer',
  );
}
