import 'dart:io';
import '../Model/Section_Model.dart';
import '../Model/User.dart';

List<User> addressList = [];
List<Promo> promoList = [];
double totalPrice = 0;
double originalPrice = 0;
double deliveryCharge = 0;
double taxPersontage = 0;
int? selectedAddress = 0;
String? selAddress;
String? paymentMethod = '';
String? selTime;
String? selDate;
String? promocode;
bool? isTimeSlot;
bool? isPromoValid = false;
bool? isUseWallet = false;
bool? isPayLayShow = true;
int? selectedTime;
int? selectedDate;
int? selectedMethod;
bool isPromoLen = false;
double promoAmount = 0;
double remWalBal = 0;
double usedBalance = 0;
List<File> prescriptionImages = [];
String? midtransPaymentMode;
String? midtransPaymentMethod;
String? midtrashClientKey;
String? midTranshMerchandId;
String? midtransServerKey;
String? myfatoorahToken;
String? myfatoorahPaymentMode;
String? myfatoorahSuccessUrl;
String? myfatoorahErrorUrl;
String? myfatoorahLanguage;
String? myfatoorahCountry;
String? razorpayId;
String? paystackId;
String? stripeId;
String? stripeSecret;
String? stripeMode = "test";
String? stripeCurCode;
String? stripePayId;
String? paytmMerId;
String? paytmMerKey;
String? phonePeMode;
String? phonePeMerId;
String? phonePeAppId;
bool payTesting = true;
List<SectionModel> saveLaterList = [];
String isStorePickUp = "false";
double codDeliverChargesOfShipRocket = 0.0;
double prePaidDeliverChargesOfShipRocket = 0.0;
bool? isLocalDelCharge;
String shipRocketDeliverableDate = '';
